# Generated by Django 2.1.7 on 2019-03-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='langCode',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
